import { Meal } from "@/components/Meal";

const meals: Meal[] = [
  // ✅ Indian Keto Breakfast Options
  {
    id: "k-breakfast-1",
    name: "Paneer Bhurji",
    description: "Scrambled paneer with spices and butter",
    calories: 450,
    nutrients: { protein: 28, carbs: 8, fats: 32 },
    image: "/pannerbhurji.jpg",
    mealType: "breakfast",
    dietType: "keto",
  },
  {
    id: "k-breakfast-2",
    name: "Egg Masala with Ghee",
    description: "Boiled eggs in a spicy Indian masala with ghee",
    calories: 520,
    nutrients: { protein: 30, carbs: 6, fats: 38 },
    image: "/eggmasala.jpg",
    mealType: "breakfast",
    dietType: "keto",
  },
  {
    id: "k-breakfast-3",
    name: "Coconut Flour Dosa",
    description: "Low-carb dosa made with coconut flour and served with chutney",
    calories: 380,
    nutrients: { protein: 15, carbs: 10, fats: 30 },
    image: "/dosa.jpg",
    mealType: "breakfast",
    dietType: "keto",
  },

  // ✅ Indian Vegan Breakfast Options
  {
    id: "v-breakfast-1",
    name: "Moong Dal Chilla",
    description: "Savory Indian pancakes made from ground moong dal",
    calories: 320,
    nutrients: { protein: 14, carbs: 45, fats: 12 },
    image: "/moongdaal.webp",
    mealType: "breakfast",
    dietType: "vegan",
  },
  {
    id: "v-breakfast-2",
    name: "Upma",
    description: "Semolina cooked with veggies and mustard seeds",
    calories: 280,
    nutrients: { protein: 10, carbs: 50, fats: 8 },
    image: "/upma.jpg",
    mealType: "breakfast",
    dietType: "vegan",
  },
  {
    id: "v-breakfast-3",
    name: "Besan Chilla",
    description: "Chickpea flour pancakes with onions and green chilies",
    calories: 340,
    nutrients: { protein: 12, carbs: 48, fats: 14 },
    image: "/besanchilla.jpg",
    mealType: "breakfast",
    dietType: "vegan",
  },

  // ✅ Indian Paleo Breakfast Options
  {
    id: "p-breakfast-1",
    name: "Egg Bhurji",
    description: "Scrambled eggs with onions, tomatoes, and chilies",
    calories: 380,
    nutrients: { protein: 22, carbs: 8, fats: 28 },
    image: "/eggbhurji.jpg",
    mealType: "breakfast",
    dietType: "paleo",
  },
  {
    id: "p-breakfast-2",
    name: "Coconut Ladoo",
    description: "Coconut balls made with jaggery and nuts",
    calories: 280,
    nutrients: { protein: 8, carbs: 18, fats: 20 },
    image: "/coconutladoo.webp",
    mealType: "breakfast",
    dietType: "paleo",
  },

  {
    id: "k-lunch-1",
    name: "Chicken Tikka with Mint Chutney",
    description: "Grilled chicken marinated in yogurt and spices",
    calories: 480,
    nutrients: { protein: 42, carbs: 5, fats: 30 },
    image: "/chickentikka.jpg",
    mealType: "lunch",
    dietType: "keto",
  },
  {
    id: "k-lunch-2",
    name: "Palak Paneer",
    description: "Paneer cubes cooked in a rich spinach gravy",
    calories: 420,
    nutrients: { protein: 25, carbs: 12, fats: 35 },
    image: "/palakpaneer.jpeg",
    mealType: "lunch",
    dietType: "keto",
  },
  {
    id: "k-lunch-3",
    name: "Mutton Korma",
    description: "Slow-cooked mutton curry with rich spices and yogurt",
    calories: 550,
    nutrients: { protein: 38, carbs: 7, fats: 42 },
    image: "/mutton.webp",
    mealType: "lunch",
    dietType: "keto",
  },

  {
    id: "k-dinner-1",
    name: "Butter Chicken (No Rice)",
    description: "Tender chicken cooked in a buttery tomato-based curry",
    calories: 600,
    nutrients: { protein: 45, carbs: 8, fats: 40 },
    image: "/butterchicken.jpg",
    mealType: "dinner",
    dietType: "keto",
  },
  {
    id: "k-dinner-2",
    name: "Fish Fry with Mint Chutney",
    description: "Crispy shallow-fried fish served with mint chutney",
    calories: 500,
    nutrients: { protein: 38, carbs: 4, fats: 35 },
    image: "/fryfish.jpg",
    mealType: "dinner",
    dietType: "keto",
  },
  {
    id: "k-dinner-3",
    name: "Tandoori Chicken with Salad",
    description: "Grilled chicken with fresh salad and mint yogurt",
    calories: 520,
    nutrients: { protein: 40, carbs: 5, fats: 28 },
    image: "/tandoorichicken.jpg",
    mealType: "dinner",
    dietType: "keto",
  },

  // ✅ Indian Vegan Lunch Options
  {
    id: "v-lunch-1",
    name: "Dal Tadka with Brown Rice",
    description: "Lentils tempered with Indian spices and served with rice",
    calories: 380,
    nutrients: { protein: 18, carbs: 50, fats: 10 },
    image: "/daltadka.jpg",
    mealType: "lunch",
    dietType: "vegan",
  },
  {
    id: "v-lunch-2",
    name: "Baingan Bharta",
    description: "Smoky mashed eggplant curry served with roti",
    calories: 420,
    nutrients: { protein: 10, carbs: 40, fats: 18 },
    image: "/bainganbharta.jpeg",
    mealType: "lunch",
    dietType: "vegan",
  },
  {
    id: "v-lunch-3",
    name: "Rajma Masala",
    description: "Kidney bean curry cooked with tomato and Indian spices",
    calories: 360,
    nutrients: { protein: 15, carbs: 55, fats: 10 },
    image: "/rajma.jpeg",
    mealType: "lunch",
    dietType: "vegan",
  },

  // ✅ Indian Paleo Lunch Options
  {
    id: "p-lunch-1",
    name: "Tandoori Chicken",
    description: "Chicken marinated with yogurt and Indian spices, grilled to perfection",
    calories: 520,
    nutrients: { protein: 45, carbs: 5, fats: 30 },
    image: "/tandoorichicken.jpg",
    mealType: "lunch",
    dietType: "paleo",
  },
  {
    id: "p-lunch-2",
    name: "Fish Curry",
    description: "Spicy coconut-based fish curry served with vegetables",
    calories: 450,
    nutrients: { protein: 38, carbs: 10, fats: 28 },
    image: "/fryfish.jpg",
    mealType: "lunch",
    dietType: "paleo",
  },

  // ✅ Indian Vegan Dinner Options
  {
    id: "v-dinner-1",
    name: "Masoor Dal with Roti",
    description: "Red lentil dal served with whole wheat roti",
    calories: 480,
    nutrients: { protein: 20, carbs: 60, fats: 8 },
    image: "/masoordal.jpg",
    mealType: "dinner",
    dietType: "vegan",
  },
  {
    id: "v-dinner-2",
    name: "Stuffed Capsicum with Quinoa",
    description: "Bell peppers stuffed with quinoa and veggies",
    calories: 420,
    nutrients: { protein: 18, carbs: 50, fats: 12 },
    image: "/capsicum.jpeg",
    mealType: "dinner",
    dietType: "vegan",
  },

  // ✅ Indian Paleo Dinner Options
  {
    id: "p-dinner-1",
    name: "Tandoori Lamb Chops",
    description: "Spiced lamb chops cooked in a tandoor",
    calories: 600,
    nutrients: { protein: 48, carbs: 6, fats: 40 },
    image: "/lambchops.jpg",
    mealType: "dinner",
    dietType: "paleo",
  },
  {
    id: "p-dinner-2",
    name: "Prawns Masala",
    description: "Spicy coconut-based prawns masala",
    calories: 500,
    nutrients: { protein: 42, carbs: 8, fats: 35 },
    image: "/prawns.jpg",
    mealType: "dinner",
    dietType: "paleo",
  },
];

export default meals;
